name: Node Tests

on:
  pull_request:

jobs:
  npm-ci:
    name: (npm) Install, build, and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npm 7
        run: npm i -g npm@7
      - name: Install node dependencies (npm ci)
        run: npm ci
      - name: Run npm lint
        run: npm run lint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
